version: "3.3"
services:
  flask:
    restart: always
    build: flask/
    depends_on:
      - "mysql"
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
  mysql:
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: flask
      MYSQL_USER: db_user
      MYSQL_USER: Passw0rd
  lb:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "flask"
  prometheus:
    restart: always
    image: bitnami/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
  mysql-exporter:
    restart: always
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: root:1234@(mysql:3306)








